# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dowjones.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dowjones.proto',
  package='dow_jones_index_proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x64owjones.proto\x12\x15\x64ow_jones_index_proto\"\x8f\x03\n\rDowJonesIndex\x12\x0f\n\x07quarter\x18\x01 \x01(\x03\x12\r\n\x05stock\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\x0c\n\x04open\x18\x04 \x01(\t\x12\x0c\n\x04high\x18\x05 \x01(\t\x12\x0b\n\x03low\x18\x06 \x01(\t\x12\r\n\x05\x63lose\x18\x07 \x01(\t\x12\x0e\n\x06volume\x18\x08 \x01(\x03\x12\x1c\n\x14percent_change_price\x18\t \x01(\t\x12*\n\"percent_change_volume_over_last_wk\x18\n \x01(\t\x12\x1d\n\x15previous_weeks_volume\x18\x0b \x01(\t\x12\x17\n\x0fnext_weeks_open\x18\x0c \x01(\t\x12\x18\n\x10next_weeks_close\x18\r \x01(\t\x12\'\n\x1fpercent_change_next_weeks_price\x18\x0e \x01(\x01\x12\x1d\n\x15\x64\x61ys_to_next_dividend\x18\x0f \x01(\x03\x12$\n\x1cpercent_return_next_dividend\x18\x10 \x01(\x01\"Q\n\x0e\x44owJonesResult\x12?\n\x11\x64ownjonesresponse\x18\x01 \x03(\x0b\x32$.dow_jones_index_proto.DowJonesIndexb\x06proto3')
)




_DOWJONESINDEX = _descriptor.Descriptor(
  name='DowJonesIndex',
  full_name='dow_jones_index_proto.DowJonesIndex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quarter', full_name='dow_jones_index_proto.DowJonesIndex.quarter', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stock', full_name='dow_jones_index_proto.DowJonesIndex.stock', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='dow_jones_index_proto.DowJonesIndex.date', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='open', full_name='dow_jones_index_proto.DowJonesIndex.open', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='high', full_name='dow_jones_index_proto.DowJonesIndex.high', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='low', full_name='dow_jones_index_proto.DowJonesIndex.low', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='close', full_name='dow_jones_index_proto.DowJonesIndex.close', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volume', full_name='dow_jones_index_proto.DowJonesIndex.volume', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='percent_change_price', full_name='dow_jones_index_proto.DowJonesIndex.percent_change_price', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='percent_change_volume_over_last_wk', full_name='dow_jones_index_proto.DowJonesIndex.percent_change_volume_over_last_wk', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='previous_weeks_volume', full_name='dow_jones_index_proto.DowJonesIndex.previous_weeks_volume', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_weeks_open', full_name='dow_jones_index_proto.DowJonesIndex.next_weeks_open', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_weeks_close', full_name='dow_jones_index_proto.DowJonesIndex.next_weeks_close', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='percent_change_next_weeks_price', full_name='dow_jones_index_proto.DowJonesIndex.percent_change_next_weeks_price', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='days_to_next_dividend', full_name='dow_jones_index_proto.DowJonesIndex.days_to_next_dividend', index=14,
      number=15, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='percent_return_next_dividend', full_name='dow_jones_index_proto.DowJonesIndex.percent_return_next_dividend', index=15,
      number=16, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=441,
)


_DOWJONESRESULT = _descriptor.Descriptor(
  name='DowJonesResult',
  full_name='dow_jones_index_proto.DowJonesResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='downjonesresponse', full_name='dow_jones_index_proto.DowJonesResult.downjonesresponse', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=524,
)

_DOWJONESRESULT.fields_by_name['downjonesresponse'].message_type = _DOWJONESINDEX
DESCRIPTOR.message_types_by_name['DowJonesIndex'] = _DOWJONESINDEX
DESCRIPTOR.message_types_by_name['DowJonesResult'] = _DOWJONESRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DowJonesIndex = _reflection.GeneratedProtocolMessageType('DowJonesIndex', (_message.Message,), dict(
  DESCRIPTOR = _DOWJONESINDEX,
  __module__ = 'dowjones_pb2'
  # @@protoc_insertion_point(class_scope:dow_jones_index_proto.DowJonesIndex)
  ))
_sym_db.RegisterMessage(DowJonesIndex)

DowJonesResult = _reflection.GeneratedProtocolMessageType('DowJonesResult', (_message.Message,), dict(
  DESCRIPTOR = _DOWJONESRESULT,
  __module__ = 'dowjones_pb2'
  # @@protoc_insertion_point(class_scope:dow_jones_index_proto.DowJonesResult)
  ))
_sym_db.RegisterMessage(DowJonesResult)


# @@protoc_insertion_point(module_scope)
